---
- name: Waiting for Engine to start
  wait_for:
#    port: 9090
    delay: 60
    timeout: 60
 #   state: started

- name: Copy restore.sql 
  template:
    src: restore.sql.j2
    dest: "/tmp/restore.sql"

- name: Update Mysql Table
  mysql_db: 
    name: bigbrain_engine
    state: import
    target: /tmp/restore.sql
    login_user: root
    login_password: root


